from __future__ import annotations

import re


TOKEN_RE = re.compile(r"[0-9A-Za-z\u0400-\u04FF]+")

STOP_WORDS = {
    "and",
    "for",
    "from",
    "html",
    "http",
    "https",
    "the",
    "www",
    "для",
    "его",
    "или",
    "как",
    "над",
    "под",
    "при",
    "про",
    "что",
    "это",
}

DOMAIN_GENERIC_TOKENS = {
    "administration",
    "agency",
    "atmospheric",
    "avito",
    "авито",
    "department",
    "government",
    "national",
    "noaa",
    "oceanic",
    "office",
    "official",
    "regional",
    "collaboration",
    "network",
    "www",
}

MARKETPLACE_GENERIC_TOKENS = {
    "ad",
    "ads",
    "all",
    "board",
    "buy",
    "catalog",
    "category",
    "feed",
    "home",
    "listing",
    "main",
    "offer",
    "offers",
    "page",
    "popular",
    "pro",
    "recommendation",
    "recommendations",
    "sale",
    "sell",
    "site",
    "товар",
    "товары",
    "каталог",
    "объявление",
    "объявления",
    "популярное",
    "рекомендация",
    "рекомендации",
    "сайт",
}

LOCATION_TOKENS = {
    "ekaterinburg",
    "kazan",
    "krasnodar",
    "moscow",
    "moskva",
    "novosibirsk",
    "piter",
    "russia",
    "russian",
    "spb",
    "ufa",
    "екатеринбург",
    "казань",
    "краснодар",
    "москва",
    "новосибирск",
    "питер",
    "россия",
    "санкт",
    "спб",
    "уфа",
}

WEAK_STRUCTURE_TOKENS = {
    "about",
    "area",
    "archive",
    "category",
    "default",
    "focus",
    "index",
    "page",
    "rubric",
    "section",
    "tag",
    "topic",
    "главная",
    "раздел",
    "рубрика",
    "страница",
}

GENERIC_HEADING_TOKENS = (
    DOMAIN_GENERIC_TOKENS
    | MARKETPLACE_GENERIC_TOKENS
    | LOCATION_TOKENS
    | WEAK_STRUCTURE_TOKENS
    | {"administration", "agency", "national", "official", "office", "главная", "весь", "все"}
)

PRODUCT_MODEL_CUES = {
    "airpods",
    "apple",
    "galaxy",
    "honor",
    "huawei",
    "iphone",
    "ipad",
    "macbook",
    "mini",
    "nintendo",
    "pixel",
    "playstation",
    "ps",
    "ps5",
    "redmi",
    "samsung",
    "sony",
    "switch",
    "ultra",
    "xiaomi",
    "xbox",
    "айфон",
    "самсунг",
    "телефон",
}

VERTICAL_GROUPS = {
    "phones": {
        "airpods",
        "apple",
        "galaxy",
        "honor",
        "huawei",
        "iphone",
        "ipad",
        "mobile",
        "mobilnye",
        "phone",
        "phones",
        "pixel",
        "redmi",
        "samsung",
        "smartphone",
        "telefony",
        "xiaomi",
        "айфон",
        "мобильный",
        "смартфон",
        "телефон",
        "телефоны",
    },
    "auto": {
        "auto",
        "autoteka",
        "avtomobili",
        "car",
        "cars",
        "moto",
        "transport",
        "авто",
        "автомобиль",
        "машина",
        "транспорт",
    },
    "realty": {
        "apartment",
        "flat",
        "house",
        "nedvizhimost",
        "realty",
        "rent",
        "квартира",
        "недвижимость",
        "дом",
        "аренда",
    },
    "jobs": {
        "job",
        "jobs",
        "rabota",
        "resume",
        "vacancy",
        "вакансия",
        "работа",
        "резюме",
    },
}

JUNK_PATH_PARTS = {
    "account",
    "cart",
    "checkout",
    "contact",
    "contact-us",
    "disclaimer",
    "filter",
    "login",
    "logout",
    "policy",
    "privacy",
    "search",
    "signin",
    "signup",
    "tag",
    "tags",
    "terms",
    "user",
}

BLOCKED_PAGE_MARKERS = {
    "access denied",
    "captcha",
    "cloudflare",
    "denied",
    "forbidden",
    "problem with ip",
    "verify you are human",
    "доступ ограничен",
    "капча",
    "проблема с ip",
    "проверка, что вы не робот",
}
