LIVE_SITEMAP_STRATEGY = "bfs + live sitemap"
SITEMAP_RECOMMENDATION_FETCH_LIMIT = 8
SITEMAP_RECOMMENDATION_RANK_LIMIT = 64
SITEMAP_WAIT_TIMEOUT_SECONDS = 12.0
VERIFIED_PARENT_FETCH_LIMIT = 4
RECOMMENDATION_PHASE_RESERVE_RATIO = 0.25
RECOMMENDATION_PHASE_MAX_SECONDS = 8.0
MAX_RECOMMENDATION_SOURCE_DEPTH = 3
